import chromadb

client = chromadb.PersistentClient(path="./chroma_db")
emb_fn = chromadb.utils.embedding_functions.SentenceTransformerEmbeddingFunction(model_name="all-MiniLM-L6-v2")

try:
    client.delete_collection("movies")
except Exception:
    pass

collection = client.get_or_create_collection(name="movies", embedding_function=emb_fn)

movie_seeds = [
    ("Inception", "Sci-Fi", "Mind-bending sci-fi thriller about dream sharing and layered realities."),
    ("Interstellar", "Sci-Fi", "Space exploration epic about survival, love, and time dilation."),
    ("The Matrix", "Sci-Fi", "Cyberpunk action story about reality, freedom, and rebellion."),
    ("Blade Runner 2049", "Sci-Fi", "Neo-noir future mystery about identity and memory."),
    ("Arrival", "Sci-Fi", "First-contact drama about language, time, and human connection."),
    ("Ex Machina", "Sci-Fi", "Psychological AI thriller about consciousness and manipulation."),
    ("Minority Report", "Sci-Fi", "Futuristic crime thriller about prediction and free will."),
    ("District 9", "Sci-Fi", "Gritty alien allegory about segregation and transformation."),
    ("The Martian", "Sci-Fi", "Optimistic survival story of science and resilience on Mars."),
    ("Dune", "Sci-Fi", "Epic desert saga of politics, prophecy, and power."),
    ("Dune: Part Two", "Sci-Fi", "Continuation of a grand sci-fi rebellion and destiny arc."),
    ("Tenet", "Sci-Fi", "Time-inversion espionage thriller with high-concept action."),
    ("Annihilation", "Sci-Fi", "Atmospheric sci-fi mystery about mutation and self-destruction."),
    ("Looper", "Sci-Fi", "Time-travel crime thriller about consequence and choice."),
    ("Edge of Tomorrow", "Sci-Fi", "Time-loop war film blending humor and tactical action."),
    ("Children of Men", "Sci-Fi", "Dystopian thriller about hope in a collapsing world."),
    ("Snowpiercer", "Sci-Fi", "Class-war allegory set aboard a perpetual motion train."),
    ("Her", "Sci-Fi", "Intimate drama about loneliness and AI companionship."),
    ("Gattaca", "Sci-Fi", "Genetic dystopia about ambition and identity."),
    ("Moon", "Sci-Fi", "Minimalist space mystery about isolation and truth."),
    ("Mad Max: Fury Road", "Action", "High-octane post-apocalyptic chase with relentless momentum."),
    ("John Wick", "Action", "Stylized revenge action with precise choreography."),
    ("John Wick: Chapter 2", "Action", "Expanded underworld action with global stakes."),
    ("John Wick: Chapter 3 - Parabellum", "Action", "Nonstop pursuit action with inventive set pieces."),
    ("John Wick: Chapter 4", "Action", "Epic martial action journey across global arenas."),
    ("The Dark Knight", "Action", "Crime superhero drama with moral conflict and chaos."),
    ("The Dark Knight Rises", "Action", "Large-scale finale about fear, sacrifice, and redemption."),
    ("The Batman", "Action", "Detective-driven noir superhero investigation."),
    ("Gladiator", "Action", "Historical revenge epic with emotional intensity."),
    ("300", "Action", "Stylized war action focused on courage and resistance."),
    ("The Raid", "Action", "Close-quarters action benchmark with intense pacing."),
    ("The Raid 2", "Action", "Expanded crime saga with brutal action craft."),
    ("Mission: Impossible - Fallout", "Action", "Spy action thriller with practical stunt spectacle."),
    ("Top Gun: Maverick", "Action", "High-speed aerial action with legacy emotion."),
    ("Casino Royale", "Action", "Rebooted spy thriller with grounded intensity."),
    ("Skyfall", "Action", "Character-focused spy action with elegant style."),
    ("No Time to Die", "Action", "Emotional spy finale with high stakes."),
    ("Extraction", "Action", "Rescue action thriller with kinetic long takes."),
    ("Nobody", "Action", "Ordinary man drawn into violent underworld conflict."),
    ("Sicario", "Action", "Border-crime thriller with tense tactical operations."),
    ("The Godfather", "Crime", "Classic mafia saga of family and power."),
    ("The Godfather Part II", "Crime", "Parallel rise-and-fall crime masterpiece."),
    ("Goodfellas", "Crime", "Fast-paced mob chronicle of glamour and brutality."),
    ("The Departed", "Crime", "Undercover crime thriller about loyalty and deception."),
    ("Heat", "Crime", "Cat-and-mouse crime epic between cop and thief."),
    ("Se7en", "Crime", "Dark serial-killer investigation with moral tension."),
    ("Zodiac", "Crime", "Procedural obsession thriller based on true crimes."),
    ("Prisoners", "Crime", "Kidnapping mystery thriller about desperation and justice."),
    ("Nightcrawler", "Crime", "Media satire thriller about ambition and ethics."),
    ("Drive", "Crime", "Moody neo-noir about violence and fragile humanity."),
    ("Shutter Island", "Thriller", "Psychological mystery with shifting perception."),
    ("Fight Club", "Thriller", "Subversive identity drama with anarchic energy."),
    ("Gone Girl", "Thriller", "Twisted relationship thriller about media and manipulation."),
    ("The Silence of the Lambs", "Thriller", "Psychological crime thriller with iconic performances."),
    ("The Prestige", "Thriller", "Rivalry mystery about obsession and illusion."),
    ("Memento", "Thriller", "Reverse-structured memory thriller about truth."),
    ("Black Swan", "Thriller", "Psychological descent in pursuit of perfection."),
    ("The Sixth Sense", "Thriller", "Supernatural mystery anchored in emotional drama."),
    ("The Girl with the Dragon Tattoo", "Thriller", "Dark investigative thriller with layered secrets."),
    ("Source Code", "Thriller", "Tense time-loop thriller solving a train bombing."),
    ("The Shawshank Redemption", "Drama", "Hopeful prison drama about friendship and perseverance."),
    ("Forrest Gump", "Drama", "Warm life-journey drama through major historical moments."),
    ("Whiplash", "Drama", "Intense mentor-student drama about ambition and cost."),
    ("The Social Network", "Drama", "Sharp drama about creation, ambition, and betrayal."),
    ("The Pursuit of Happyness", "Drama", "Inspirational struggle against poverty and hardship."),
    ("The Green Mile", "Drama", "Supernatural prison drama with compassion and grief."),
    ("A Beautiful Mind", "Drama", "Biographical drama about genius and resilience."),
    ("The Pianist", "Drama", "War survival drama of endurance and artistry."),
    ("The Imitation Game", "Drama", "Historical drama about codebreaking and secrecy."),
    ("Marriage Story", "Drama", "Intimate relationship drama about love and separation."),
    ("Titanic", "Romance", "Epic romance set against maritime disaster."),
    ("La La Land", "Romance", "Modern musical romance about dreams and compromise."),
    ("Pride and Prejudice", "Romance", "Period romance driven by wit and social pressure."),
    ("Before Sunrise", "Romance", "Conversational romance over one unforgettable night."),
    ("Before Sunset", "Romance", "Reflective reunion romance exploring paths not taken."),
    ("Before Midnight", "Romance", "Mature romance examining long-term commitment."),
    ("Notting Hill", "Romance", "Charming romance between a bookseller and a star."),
    ("About Time", "Romance", "Time-travel romance about family and gratitude."),
    ("The Notebook", "Romance", "Melodramatic love story spanning years and memory."),
    ("500 Days of Summer", "Romance", "Nonlinear relationship story about expectations and growth."),
    ("The Grand Budapest Hotel", "Comedy", "Stylized comedy adventure with whimsical charm."),
    ("Knives Out", "Comedy", "Witty murder mystery with playful twists."),
    ("The Nice Guys", "Comedy", "Buddy detective comedy with chaotic momentum."),
    ("Superbad", "Comedy", "Coming-of-age teen comedy about friendship and awkwardness."),
    ("The Hangover", "Comedy", "Outrageous mystery-comedy after a wild night."),
    ("Palm Springs", "Comedy", "Time-loop romantic comedy with existential humor."),
    ("Groundhog Day", "Comedy", "Classic time-loop comedy about self-improvement."),
    ("Jojo Rabbit", "Comedy", "Satirical wartime comedy balancing humor and empathy."),
    ("Booksmart", "Comedy", "Energetic coming-of-age comedy about friendship."),
    ("The Big Lebowski", "Comedy", "Cult comedy noir with laid-back absurdity."),
    ("Spirited Away", "Animation", "Magical coming-of-age fantasy in a spirit world."),
    ("Your Name", "Animation", "Body-swap romance with cosmic mystery."),
    ("Spider-Man: Into the Spider-Verse", "Animation", "Inventive multiverse superhero animation."),
    ("Toy Story", "Animation", "Beloved adventure about friendship and loyalty."),
    ("Toy Story 3", "Animation", "Emotional animated farewell about growing up."),
    ("Coco", "Animation", "Colorful musical journey through memory and family."),
    ("How to Train Your Dragon", "Animation", "Adventure about empathy and unexpected friendship."),
    ("Ratatouille", "Animation", "Food-focused comedy about passion and creativity."),
    ("Inside Out", "Animation", "Imaginative emotional adventure inside the mind."),
    ("Wall-E", "Animation", "Quiet sci-fi romance about care and restoration."),
    ("The Conjuring", "Horror", "Supernatural horror with haunted-house dread."),
    ("The Conjuring 2", "Horror", "Paranormal sequel with atmospheric scares."),
    ("Hereditary", "Horror", "Disturbing family horror about grief and fate."),
    ("Midsommar", "Horror", "Daylight folk horror about trauma and belonging."),
    ("A Quiet Place", "Horror", "Tense survival horror where silence is survival."),
    ("A Quiet Place Part II", "Horror", "Expanded survival horror with new threats."),
    ("Get Out", "Horror", "Social horror thriller exposing hidden menace."),
    ("Us", "Horror", "Duality-themed horror about identity and fear."),
    ("The Babadook", "Horror", "Psychological horror rooted in grief and motherhood."),
    ("It", "Horror", "Coming-of-age horror confronting an ancient evil."),
    ("The Lord of the Rings: The Fellowship of the Ring", "Fantasy", "Epic quest begins in a richly built fantasy world."),
    ("The Lord of the Rings: The Two Towers", "Fantasy", "Middle chapter of war, loyalty, and endurance."),
    ("The Lord of the Rings: The Return of the King", "Fantasy", "Grand finale of sacrifice and triumph."),
    ("Harry Potter and the Sorcerer's Stone", "Fantasy", "Magical school adventure and discovery."),
    ("Harry Potter and the Prisoner of Azkaban", "Fantasy", "Darker magical mystery with emotional depth."),
    ("Pan's Labyrinth", "Fantasy", "Dark fairy-tale fantasy set during wartime."),
    ("The Shape of Water", "Fantasy", "Romantic fantasy about empathy and otherness."),
    ("Stardust", "Fantasy", "Adventure fantasy with charm and humor."),
    ("The Chronicles of Narnia: The Lion, the Witch and the Wardrobe", "Fantasy", "Family fantasy adventure in a magical realm."),
    ("Doctor Strange", "Fantasy", "Mystic superhero fantasy about transformation."),
    ("Saving Private Ryan", "War", "Intense war drama focused on mission and sacrifice."),
    ("1917", "War", "Immersive one-shot style war journey."),
    ("Dunkirk", "War", "Evacuation war thriller across land, sea, and air."),
    ("Hacksaw Ridge", "War", "True-story war drama about courage without violence."),
    ("Fury", "War", "Tank crew war drama under extreme pressure."),
    ("Apocalypse Now", "War", "Surreal war odyssey into moral darkness."),
    ("Platoon", "War", "Ground-level war drama about conflict and conscience."),
    ("The Hurt Locker", "War", "Bomb-disposal war thriller with psychological tension."),
    ("Letters from Iwo Jima", "War", "War perspective drama with human complexity."),
    ("All Quiet on the Western Front", "War", "Anti-war drama showing the cost of conflict."),
]
tv_seeds = [
    ("Breaking Bad", "Crime", "A chemistry teacher turned methamphetamine kingpin."),
    ("Game of Thrones", "Fantasy", "Noble families fight for control of the mythical land of Westeros."),
    ("Stranger Things", "Sci-Fi", "A group of kids uncover supernatural forces and secret government exploits."),
    ("The Office", "Comedy", "A mockumentary on a group of typical office workers."),
    ("The Wire", "Crime", "The Baltimore drug scene, seen through the eyes of drug dealers and law enforcement."),
    ("Chernobyl", "Drama", "A dramatization of the true story of the 1986 nuclear accident."),
    ("The Sopranos", "Crime", "New Jersey mob boss deals with personal and professional issues."),
    ("Black Mirror", "Sci-Fi", "An anthology series exploring a twisted, high-tech multiverse."),
    ("Succession", "Drama", "A dysfunctional global-media family fights for control of the company."),
    ("True Detective", "Crime", "Police investigations unearth the personal and professional secrets of those involved."),
]

media_items = []

for index, (title, genre, desc) in enumerate(movie_seeds, start=1):
    media_items.append({
        "id": f"movie_seed_{index}",
        "title": title,
        "desc": f"{title}: {desc}",
        "genre": genre,
        "type": "movie"
    })

for index, (title, genre, desc) in enumerate(tv_seeds, start=1):
    media_items.append({
        "id": f"tv_seed_{index}",
        "title": title,
        "desc": f"{title}: {desc}",
        "genre": genre,
        "type": "tv"
    })

collection.upsert(
    ids=[m["id"] for m in media_items],
    documents=[m["desc"] for m in media_items],
    metadatas=[{"title": m["title"], "genre": m["genre"], "type": m["type"]} for m in media_items],
)

print(f"Ingestion complete! Added {len(movie_seeds)} movies and {len(tv_seeds)} TV shows.")